DEFAULTS: &DEFAULTS
  twitter_key: WycY9agKD1UlKRMDwdowzAavr
  twitter_secret: 5b6Tvzb5D6h33llpZmlMyn5TdVhGGYNCJrUruQLx8x7hX3B1e8

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS
  
